apiVersion: v1
kind: Service
metadata:
  name: {{ include "janisterminal.fullname" . }}-service
  labels:
    {{- include "janisterminal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "janisterminal.selectorLabels" . | nindent 4 }}
